version: "3"
services:
  textgen:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    container_name: textgen
    
  db:
    image: postgres
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    expose:
        - "5400"
    ports:
        - "5400:5432"